# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-17 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello_world', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stufftorate',
            name='color',
            field=models.CharField(default='Green', max_length=100),
            preserve_default=False,
        ),
    ]
