# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-06 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello_world', '0004_auto_20160927_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='multi_rating',
            field=models.CommaSeparatedIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], max_length=250, null=True),
        ),
    ]
