# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello_world', '0006_auto_20160929_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='breed',
            field=models.CharField(default='Dog', max_length=200),
            preserve_default=False,
        ),
    ]
