# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-11 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello_world', '0008_customer_mileage'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='week_day',
            field=models.CharField(choices=[('sun', 'Sunday'), ('mon', 'Monday'), ('tues', 'Tuesday'), ('wed', 'Wednesday'), ('thurs', 'Thursday')], default='sun', max_length=20),
            preserve_default=False,
        ),
    ]
